apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    postgres: deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      postgres: deploy
  template:
    metadata:
      labels:
        postgres: deploy
    spec:
      containers:
        - name: postgres-pod
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "adham"
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "devopsDB"
          volumeMounts:
            - name: postgres-vol
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-vol
          PersistentVolumeClaim:
            claimName: postgres-pvc        
